# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='initial', max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileBackupError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=255)),
                ('azure_path', models.CharField(max_length=255)),
                ('retry', models.BooleanField(default=True)),
                ('retries', models.IntegerField(default=0)),
                ('file_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_azure_backup.FileBackup')),
            ],
        ),
    ]
